# Generated by Django 4.2.16 on 2025-10-07 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('clients', '0001_initial'),
        ('commandes', '0002_alter_boncommande_taux_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.Fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='type_commande',
            field=models.CharField(choices=[('achat', 'Achat fournisseur'), ('vente', 'Vente client')], default='achat', max_length=10, verbose_name='Type de commande'),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Client'),
        ),
    ]
