# Generated by Django 4.2.16 on 2025-10-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_boncommande_fournisseur_boncommande_type_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro de commande'),
        ),
    ]
