# Generated by Django 4.2.16 on 2025-10-08 09:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_alter_boncommande_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant TTC'),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant TVA'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='prix_unitaire_ht',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire HT'),
        ),
    ]
