# Generated by Django 5.2.5 on 2025-09-04 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Nom de la catégorie', max_length=100, unique=True, verbose_name='Libellé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Catégorie active')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['libelle'],
                'indexes': [models.Index(fields=['libelle'], name='articles_ca_libelle_90e53c_idx'), models.Index(fields=['actif'], name='articles_ca_actif_c3aa3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text="Nom de l'article", max_length=200, verbose_name='Désignation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Article actif')),
                ('categorie', models.ForeignKey(help_text="Catégorie de l'article", on_delete=django.db.models.deletion.CASCADE, to='articles.Categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['designation'],
                'indexes': [models.Index(fields=['designation'], name='articles_ar_designa_be39bb_idx'), models.Index(fields=['categorie'], name='articles_ar_categor_6bea64_idx'), models.Index(fields=['actif'], name='articles_ar_actif_d09ea0_idx')],
            },
        ),
    ]
