# Generated by Django 5.2.5 on 2025-08-21 11:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationsSociete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_raison_sociale', models.CharField(max_length=200, verbose_name='Nom ou raison sociale')),
                ('telephone_fixe', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone fixe')),
                ('telephone_portable', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone portable')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal')),
                ('pays', models.CharField(default='Guinée', max_length=100, verbose_name='Pays')),
                ('url_site', models.URLField(blank=True, null=True, verbose_name='URL du site web')),
                ('en_tete_document', models.TextField(blank=True, null=True, verbose_name='En-tête pour documents')),
                ('pied_page_document', models.TextField(blank=True, null=True, verbose_name='Pied de page pour documents')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Logo de la société')),
                ('numero_registre_commerce', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de registre de commerce')),
                ('numero_contribuable', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de contribuable')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informations de la société',
                'verbose_name_plural': 'Informations de la société',
            },
        ),
        migrations.CreateModel(
            name='ParametresGeneraux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbole_monetaire', models.CharField(choices=[('GNF', 'GNF (Franc Guinéen)'), ('FCFA', 'FCFA (Franc CFA)'), ('EUR', 'EUR (Euro)'), ('USD', 'USD (Dollar US)'), ('GBP', 'GBP (Livre Sterling)'), ('JPY', 'JPY (Yen Japonais)'), ('CHF', 'CHF (Franc Suisse)'), ('CAD', 'CAD (Dollar Canadien)'), ('AUD', 'AUD (Dollar Australien)')], default='GNF', max_length=10, verbose_name='Symbole monétaire')),
                ('nom_application', models.CharField(default='DEVDRECO SOFT', max_length=100, verbose_name="Nom de l'application")),
                ('elements_par_page', models.PositiveIntegerField(default=20, verbose_name='Éléments par page')),
                ('format_date', models.CharField(default='d/m/Y', max_length=20, verbose_name='Format de date')),
                ('notifications_email', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('notifications_sms', models.BooleanField(default=False, verbose_name='Notifications par SMS')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres généraux',
                'verbose_name_plural': 'Paramètres généraux',
            },
        ),
        migrations.CreateModel(
            name='UtilisateurCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('standard', 'Utilisateur standard')], default='standard', max_length=20, verbose_name='Rôle utilisateur')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('poste', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste occupé')),
                ('departement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Département')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur Django')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
