# Generated by Django 4.2.16 on 2025-09-15 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationssociete',
            name='bandeau_entete',
            field=models.ImageField(blank=True, null=True, upload_to='bandeaux/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name="Image d'entête (bandeau)"),
        ),
        migrations.AddField(
            model_name='informationssociete',
            name='bandeau_pied',
            field=models.ImageField(blank=True, null=True, upload_to='bandeaux/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image de pied de page (bandeau)'),
        ),
        migrations.AlterField(
            model_name='informationssociete',
            name='en_tete_document',
            field=models.TextField(blank=True, null=True, verbose_name='En-tête pour documents (texte)'),
        ),
        migrations.AlterField(
            model_name='informationssociete',
            name='pied_page_document',
            field=models.TextField(blank=True, null=True, verbose_name='Pied de page pour documents (texte)'),
        ),
    ]
