# Generated by Django 5.2.5 on 2025-08-21 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(help_text='Nom complet pour un particulier ou raison sociale pour une entreprise', max_length=200, verbose_name='Nom complet ou raison sociale')),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20, verbose_name='Type de client')),
                ('telephone', models.CharField(help_text='Ex.: +224 626402000', max_length=32, verbose_name='Numéro de téléphone')),
                ('telephone_normalise', models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Chiffres uniquement pour recherche', max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Adresse e-mail')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse complète')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Client actif')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['nom_complet'], name='clients_cli_nom_com_04f1dd_idx'), models.Index(fields=['telephone'], name='clients_cli_telepho_8c69d9_idx'), models.Index(fields=['telephone_normalise'], name='clients_cli_telepho_177753_idx'), models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'), models.Index(fields=['type_client'], name='clients_cli_type_cl_31a5f5_idx'), models.Index(fields=['actif'], name='clients_cli_actif_a04af9_idx')],
            },
        ),
    ]
