# Generated by Django 5.2.4 on 2025-10-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pays',
            field=models.CharField(default='Guinée', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(default='+224 ', help_text='Ex.: +224 626402000', max_length=32, verbose_name='Numéro de téléphone'),
        ),
    ]
