# Generated by Django 4.2.16 on 2025-10-02 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la permission')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code de la permission')),
                ('module', models.CharField(choices=[('clients', 'Clients'), ('devis', 'Devis'), ('factures', 'Factures'), ('commandes', 'Commandes'), ('articles', 'Articles'), ('fournisseurs', 'Fournisseurs'), ('rapports', 'Rapports'), ('parametres', 'Paramètres'), ('utilisateurs', 'Utilisateurs')], max_length=20, verbose_name='Module')),
                ('action', models.CharField(choices=[('view', 'Voir'), ('add', 'Ajouter'), ('change', 'Modifier'), ('delete', 'Supprimer'), ('export', 'Exporter'), ('import', 'Importer'), ('print', 'Imprimer')], max_length=20, verbose_name='Action')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Permission active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'action'],
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du rôle')),
                ('description', models.TextField(blank=True, verbose_name='Description du rôle')),
                ('type_role', models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('standard', 'Utilisateur standard'), ('readonly', 'Lecture seule')], default='standard', max_length=20, verbose_name='Type de rôle')),
                ('actif', models.BooleanField(default=True, verbose_name='Rôle actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='UtilisateurPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accordee', models.BooleanField(default=True, verbose_name='Permission accordée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.Permission', verbose_name='Permission')),
            ],
            options={
                'verbose_name': 'Permission utilisateur',
                'verbose_name_plural': 'Permissions utilisateurs',
                'ordering': ['utilisateur', 'permission'],
            },
        ),
        migrations.CreateModel(
            name='UtilisateurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('poste', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste occupé')),
                ('departement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Département')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('permissions_personnalisees', models.ManyToManyField(blank=True, through='utilisateurs.UtilisateurPermission', to='utilisateurs.Permission', verbose_name='Permissions personnalisées')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='utilisateurs.Role', verbose_name='Rôle principal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur Django')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.AddField(
            model_name='utilisateurpermission',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.UtilisateurProfile', verbose_name='Utilisateur'),
        ),
        migrations.CreateModel(
            name='ConnexionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('date_connexion', models.DateTimeField(auto_now_add=True, verbose_name='Date de connexion')),
                ('date_deconnexion', models.DateTimeField(blank=True, null=True, verbose_name='Date de déconnexion')),
                ('reussie', models.BooleanField(default=True, verbose_name='Connexion réussie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Connexion utilisateur',
                'verbose_name_plural': 'Connexions utilisateurs',
                'ordering': ['-date_connexion'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='utilisateurpermission',
            unique_together={('utilisateur', 'permission')},
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accordee', models.BooleanField(default=True, verbose_name='Permission accordée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='utilisateurs.Permission', verbose_name='Permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='utilisateurs.Role', verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Permission de rôle',
                'verbose_name_plural': 'Permissions de rôles',
                'ordering': ['role', 'permission'],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
