# Generated by Django 5.2.5 on 2025-08-21 11:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Numéro')),
                ('objet', models.CharField(max_length=200, verbose_name='Objet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant TTC')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validite', models.DateField(verbose_name='Date de validité')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('conditions_paiement', models.TextField(blank=True, verbose_name='Conditions de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantité')),
                ('unite', models.CharField(default='unité', max_length=20, verbose_name='Unité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix unitaire HT')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant HT')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.Devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
            },
        ),
    ]
