# Generated by Django 4.2.16 on 2025-09-28 11:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='Taux TVA (%)'),
        ),
    ]
