# Generated by Django 5.2.4 on 2025-10-01 17:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_alter_devis_taux_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Montant TTC'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Montant TVA'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='prix_unitaire_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prix unitaire HT'),
        ),
    ]
