# Generated by Django 4.2.16 on 2025-09-20 12:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(help_text="Nom du fournisseur ou raison sociale de l'entreprise", max_length=200, verbose_name='Nom complet ou raison sociale')),
                ('type_fournisseur', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('grossiste', 'Grossiste'), ('fabricant', 'Fabricant'), ('importateur', 'Importateur')], default='entreprise', max_length=20, verbose_name='Type de fournisseur')),
                ('telephone', models.CharField(help_text='Numéro de téléphone avec indicatif pays', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse complète')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='Pays')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('contact_principal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact principal')),
                ('fonction_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction du contact')),
                ('conditions_paiement', models.CharField(blank=True, help_text='Ex: 30 jours net, 2% 10 jours, etc.', max_length=200, null=True, verbose_name='Conditions de paiement')),
                ('delai_livraison', models.CharField(blank=True, help_text='Ex: 5-7 jours ouvrés', max_length=100, null=True, verbose_name='Délai de livraison')),
                ('actif', models.BooleanField(default=True, verbose_name='Fournisseur actif')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes internes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='ProduitFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_fournisseur', models.CharField(blank=True, help_text='Référence du produit chez le fournisseur', max_length=100, null=True, verbose_name='Référence fournisseur')),
                ('prix_achat_ht', models.DecimalField(decimal_places=2, help_text="Prix d'achat hors taxes", max_digits=12, verbose_name="Prix d'achat HT")),
                ('devise', models.CharField(default='XOF', help_text='Code devise (XOF, EUR, USD, etc.)', max_length=3, verbose_name='Devise')),
                ('delai_livraison', models.PositiveIntegerField(default=0, help_text='Délai de livraison en jours', verbose_name='Délai de livraison (jours)')),
                ('quantite_minimale', models.PositiveIntegerField(default=1, verbose_name='Quantité minimale de commande')),
                ('stock_disponible', models.PositiveIntegerField(default=0, help_text='Stock disponible chez le fournisseur', verbose_name='Stock disponible')),
                ('actif', models.BooleanField(default=True, verbose_name='Produit actif')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='articles.Article', verbose_name='Article')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='fournisseurs.Fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Produit fournisseur',
                'verbose_name_plural': 'Produits fournisseurs',
                'ordering': ['fournisseur__nom_complet', 'article__designation'],
            },
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['nom_complet'], name='fournisseur_nom_com_e08904_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['type_fournisseur'], name='fournisseur_type_fo_09c5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['actif'], name='fournisseur_actif_74f7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='produitfournisseur',
            index=models.Index(fields=['fournisseur', 'actif'], name='fournisseur_fournis_670388_idx'),
        ),
        migrations.AddIndex(
            model_name='produitfournisseur',
            index=models.Index(fields=['article', 'actif'], name='fournisseur_article_1f17e4_idx'),
        ),
        migrations.AddIndex(
            model_name='produitfournisseur',
            index=models.Index(fields=['prix_achat_ht'], name='fournisseur_prix_ac_934179_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produitfournisseur',
            unique_together={('fournisseur', 'article')},
        ),
    ]
