# Generated by Django 5.2.4 on 2025-10-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='pays',
            field=models.CharField(default='Guinée', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(default='+224 ', help_text='Numéro de téléphone avec indicatif pays', max_length=20, verbose_name='Téléphone'),
        ),
    ]
