# Generated by Django 4.2.16 on 2025-09-20 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(default='DEVDRECO SOFT', max_length=200, verbose_name='Nom de la société')),
                ('logo_rapport', models.ImageField(blank=True, null=True, upload_to='rapports/logos/', verbose_name='Logo pour les rapports')),
                ('couleur_principale', models.CharField(default='#007bff', max_length=7, verbose_name='Couleur principale')),
                ('couleur_secondaire', models.CharField(default='#6c757d', max_length=7, verbose_name='Couleur secondaire')),
                ('inclure_entete', models.BooleanField(default=True, verbose_name="Inclure l'en-tête")),
                ('inclure_pied', models.BooleanField(default=True, verbose_name='Inclure le pied de page')),
                ('format_date', models.CharField(default='%d/%m/%Y', max_length=20, verbose_name='Format de date')),
                ('devise', models.CharField(default='FCFA', max_length=10, verbose_name='Devise')),
            ],
            options={
                'verbose_name': 'Configuration des rapports',
                'verbose_name_plural': 'Configurations des rapports',
            },
        ),
        migrations.CreateModel(
            name='RapportVentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du rapport')),
                ('type_rapport', models.CharField(choices=[('journalier', 'Journalier'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel'), ('personnalise', 'Période personnalisée')], default='mensuel', max_length=20)),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('format_sortie', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('inclure_devis', models.BooleanField(default=True, verbose_name='Inclure les devis')),
                ('inclure_factures', models.BooleanField(default=True, verbose_name='Inclure les factures')),
                ('inclure_commandes', models.BooleanField(default=True, verbose_name='Inclure les commandes')),
                ('groupe_par_client', models.BooleanField(default=False, verbose_name='Grouper par client')),
                ('groupe_par_article', models.BooleanField(default=False, verbose_name='Grouper par article')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fichier_genere', models.FileField(blank=True, null=True, upload_to='rapports/ventes/')),
                ('creer_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Rapport de ventes',
                'verbose_name_plural': 'Rapports de ventes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RapportFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du rapport')),
                ('type_rapport', models.CharField(choices=[('ca', "Chiffre d'affaires"), ('benefices', 'Bénéfices'), ('tresorerie', 'Trésorerie'), ('complet', 'Rapport financier complet')], default='complet', max_length=20)),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('format_sortie', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('inclure_graphiques', models.BooleanField(default=True, verbose_name='Inclure les graphiques')),
                ('inclure_details', models.BooleanField(default=True, verbose_name='Inclure les détails')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fichier_genere', models.FileField(blank=True, null=True, upload_to='rapports/financiers/')),
                ('creer_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Rapport financier',
                'verbose_name_plural': 'Rapports financiers',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RapportClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du rapport')),
                ('type_rapport', models.CharField(choices=[('actifs', 'Clients actifs'), ('inactifs', 'Clients inactifs'), ('tous', 'Tous les clients'), ('nouveaux', 'Nouveaux clients'), ('fideles', 'Clients fidèles')], default='tous', max_length=20)),
                ('periode_debut', models.DateField(blank=True, null=True, verbose_name='Période début')),
                ('periode_fin', models.DateField(blank=True, null=True, verbose_name='Période fin')),
                ('format_sortie', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('inclure_statistiques', models.BooleanField(default=True, verbose_name='Inclure les statistiques')),
                ('inclure_historique_achats', models.BooleanField(default=False, verbose_name="Inclure l'historique des achats")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fichier_genere', models.FileField(blank=True, null=True, upload_to='rapports/clients/')),
                ('creer_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Rapport clients',
                'verbose_name_plural': 'Rapports clients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RapportArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du rapport')),
                ('type_rapport', models.CharField(choices=[('stock', 'État des stocks'), ('ventes', 'Articles les plus vendus'), ('moins_vendus', 'Articles moins vendus'), ('categorie', 'Par catégorie'), ('prix', 'Analyse des prix')], default='stock', max_length=20)),
                ('periode_debut', models.DateField(blank=True, null=True, verbose_name='Période début')),
                ('periode_fin', models.DateField(blank=True, null=True, verbose_name='Période fin')),
                ('format_sortie', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('inclure_categories', models.BooleanField(default=True, verbose_name='Inclure les catégories')),
                ('inclure_prix', models.BooleanField(default=True, verbose_name='Inclure les prix')),
                ('inclure_statistiques', models.BooleanField(default=True, verbose_name='Inclure les statistiques')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fichier_genere', models.FileField(blank=True, null=True, upload_to='rapports/articles/')),
                ('creer_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Rapport articles',
                'verbose_name_plural': 'Rapports articles',
                'ordering': ['-date_creation'],
            },
        ),
    ]
