# Generated by Django 4.2.16 on 2025-09-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationrapport',
            name='devise',
            field=models.CharField(default='GNF', max_length=10, verbose_name='Devise'),
        ),
    ]
